### ISSUE TITLE
[Visão] Introdução

### ISSUE THREAD

**Issue by digows** [deyvidalex/Vit-Eclesia#8]
Lugar inadequado para a menção abaixo:

> O Cadastro dos visitantes manterá as seguintes informações: se os visitantes almejam receber visita do pastor, ou algum dirigente da igreja, quantas visitas ele já vez há igreja, se ele gostaria de ser anunciado para receber o Bem Vindo da Igreja, endereço, contatos, e melhor horário/dia para visita.
> Cadastro de Membros manterá: nome, documento, endereço.
> O sistema também manterá as informações de contribuições como:
> Ofertas contendo a data da contribuição, valor e uma referência dessa contribuição, por exemplo: culto de oração.
> Dízimos contendo a data da contribuição, valor e será referenciado ao contribuinte já cadastrado ao sistema,

**Comment by deyvidalex** [comment]
Corrigido, porem achei que ficou pequena a introdução, se for necessário acrescentar algo reabra essa notificação.
